### ISSUE TITLE
requestsPerSecond

### ISSUE THREAD

**Issue by mrhhug** [roelvan/rest-sms-android#1]
What is requestsPerSecond in index.js ? How can I do less less requests per second? making that number larger or smaller? This is a powerful tool and I plan on using it tomorrow, just didn't want to get marked as spam from my provider since I only have a small number of SMS messages to send out, I want to send about two requests per minute.

I haven't done much in Node.js, have you published (or need help with) a REST API for the android app(REST SMS Gateway)?

**Comment by roelvan** [comment]
My script uses the https://www.npmjs.com/package/promise-throttle package to make sure not too many requests are sent to your phone. In this case I set it to 0.1 per second, which means at max 10 smses per second will be sent. I had very good results with this setting and delivery was very good.

**Comment by roelvan** [comment]
The app has an api itself which you can refer to (list of endpoints). This repo is an example implementation of how to use their app with node js. For me the throttling was important and I just shared this repo for other people to help get started.
